# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Error-TryCatch
version:      0.04
version_from: lib\Error\TryCatch.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Filter::Simple:                0
    Parse::RecDescent:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
